version: "3.8"

services:
  extraction:
    container_name: squadlanes
    build:
      context: extraction
      dockerfile: Dockerfile-extraction
    volumes:
      - "/PATH/TO/SQUAD:/opt/squadgame"
      - "/PATH/TO/HLP:/opt/HLP"
      - "./:/opt/squadlanes"
      
  web:
    container_name: squadlanes_web
    build:
      context: .
      dockerfile: docker/Dockerfile-node
    tty: true
    volumes:
      - "./:/opt/squadlanes-web"
    ports:
      - "1234:1234"