FROM python:3.10-bullseye

# Set wine architecture to x64
ENV WINEARCH=win64

# Install wine
RUN wget -nc https://dl.winehq.org/wine-builds/winehq.key \
    && apt-key add winehq.key \
    && echo 'deb https://dl.winehq.org/wine-builds/debian/ bullseye main' >> /etc/apt/sources.list
RUN dpkg --add-architecture i386
RUN apt update && apt install -y --install-recommends \
    gnupg2 \
    winehq-stable

# Install latest poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add root home to path where poetry was installed
ENV PATH="/root/.local/bin:${PATH}"

# Install poetry environment
COPY . /opt/squadlanes
WORKDIR /opt/squadlanes/extraction
RUN poetry config virtualenvs.in-project false
RUN poetry install

ENTRYPOINT [ "sleep", "infinity" ]